### ISSUE TITLE
expo-gl is not working to show a picture in camera roll on Android

### ISSUE THREAD

**Issue by JinHoSo** [expo/expo-gl#1]
When I try to show a picture in camera roll on Android,  
It shows error message as below

<img width="318" alt="2018-09-01 5 51 09" src="https://user-images.githubusercontent.com/31269303/44967583-55cbea00-af7d-11e8-8c78-f904cc511122.png">

I guess using cache in expo-gl has the problem because of this function ```AssetUtils.resolveAsync()``` don't return anything.

**Comment by EvanBacon** [comment]
It seems like maybe you are passing an invalid image uri to the function. You can get a `localUri` like so:
```
const asset = Expo.Asset.fromModule(require('../image.png'));
await asset.downloadAsync()
asset.localUri // Use this
```

But being that it is from camera roll you may have to re-write the image to a new location to use it. (because of the `content://`) [`expo-asset-utils`](https://github.com/expo/expo-asset-utils) can do this automatically.

**Comment by JinHoSo** [comment]
Thanks @EvanBacon 
But I'm still having this issue even the file location is starting with 'file://' 
I have tried to copy the file to another place or create a new image file, but it doesn't work
The weird thing is even I tried to use 'http://' like `AssetUtils.resolveAsync('https://i.imgur.com/5EOyTDQ.jpg');` on Android, it doesn't work as well


```
    import AssetUtils from 'expo-asset-utils'
    import {ImageManipulator} from 'expo'

    const manipResult = await ImageManipulator.manipulate(picture.uri, [{resize: {width:320}}], {
      format: 'jpeg',
    })
     
    /*
       manipResult structure
      {
         "hash": "50fb69111cd4244729c9566b874b52cc",
         "name": "90bc7ab0-4b39-49b8-9eec-abec76e51158.jpg",
         **"uri": "file:///data/user/0/today.unless.release/cache/ExperienceData/%2540rustykey%252Funless/ImageManipulator/90bc7ab0-4b39-49b8-9eec-abec76e51158.jpg",**
        }
    */

    const asset = await AssetUtils.fileInfoAsync(manipResult.uri);
    //await AssetUtils.resolveAsync(manipResult.uri) is not working as well
    console.log(asset)
```


the console.log reulst
```
[Unhandled promise rejection: Error: unexpected url: file:///data/user/0/today.unless.release/cache/ExperienceData/%2540rustykey%252Funless/ImageManipulator/90bc7ab0-4b39-49b8-9eec-abec76e51158.jpg]
```

**Comment by JinHoSo** [comment]
@EvanBacon Can you check that issue when you are free? Thanks in advance

https://github.com/expo/expo-pixi/issues/36

**Comment by tsapeta** [comment]
Alright, so looks like this issue is not related to `expo-gl` itself, so I'm closing this issue. Thanks @JinHoSo for your investigation 😉
